linters-settings:
  gofmt:
    # disable gofmt for CLI folder
    enabled: false
  golint:
    # disable golint for CLI folder
    enabled: false
  gosec:
    # disable gosec for CLI folder
    enabled: false
  # unused:
  #   # disable unused for CLI folder
  #   enabled: false

run:
  # only include files in CLI directory
  # include:
  #   - CLI/**
