#!/bin/bash

# URL PATTERN GOTTEN FROM CHATGPT
urlPattern='^(http|https)://[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?$'
dir='CLI/'
filePathPattern='^(.+)\/([^\/]+)$'

help() {
  echo 'Usage: ./run [install|build|URL_FILE|FILEPATH|test]'
  echo '------------ Sample Commands ----------------------'
  echo 'install  - Installs any dependencies in userland'
  echo 'build    - Completes any compilation needed'
  echo 'URL_FILE - Main function - rates a repo'
  echo 'FILEPATH - Main function - rates all repos in file'
  echo 'test     - Runs test suite'
  echo '---------------------------------------------------'
}

if [ -z "$1" ]; then
  echo -e "\033[31mERROR: No argument passed.\033[0m"
  help
  exit 1
elif [ $1 == 'install' ]; then
  echo 'INSTALLING DEPENDENCIES'
  cd $dir
  make install
  exit 0
elif [ $1 == 'build' ]; then
  echo 'BUILDING'
  cd $dir
  make build
  exit 0
elif [ $1 == 'test' ]; then
  echo 'TESTING'
  cd CLI
  make test
  exit 0
elif [ $1 == 'URL_FILE' ]; then
  echo 'RUNNING'
  cd $dir
  make url
  exit 0
elif [ $1 = 'help' ]; then
  help
  exit 0
elif [[ $1 =~ $filePathPattern ]]; then
  echo "FILEPATH_PATTERN"
  (cd CLI ; ./run $1)
  exit 0
# Deprecated
# elif [[ $1 =~ $urlPattern ]]; then
#   echo "URL_PATTERN $1"
#   ( cd CLI ; go run ./cmd/todo -search $1)
#   exit 0
else
  echo -e "\033[31mINVALID COMMAND: '$1'\033[0m"
  help
  exit 1
fi
