name: CI

on:
  push:
    tags:
      - v*
    branches: ['*']
  pull_request:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
  lint:
    needs: setup-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          args: --config=.golangci-config.yml

  unit-test:
    needs: [setup-go, lint]
    runs-on: ubuntu-latest
    if: ${{ needs.lint.result == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "LOG_LEVEL=1" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run Tests
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
        run: ./run test

  automated-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "12526796-5ee080c6-6247-442b-b48c-2b2d1a50cf3a"
