name: CI

on:
  push:
    tags:
      - v*
    branches: ['*']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          args: --config=.golangci-config.yml

  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ needs.lint.result == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Set environment variables
        run: |
          echo "LOG_LEVEL=1" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run Tests
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
        run: ./run test
  end-to-end-tests:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Start Server
        run: |
          go run main.go &> /dev/null &
          sleep 5

      - name: Run API tests
        run: |
          postman collection run "12526796-1455da38-eef8-4f88-8bd4-f25b437df635"

      - name: Stop Server
        run: |
          kill $(lsof -t -i:8000)
