name: CI

on:
  push:
  pull_request:

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          args: --config=.golangci-config.yml

  unit-test:
    needs: lint-go
    runs-on: ubuntu-latest
    if: ${{ needs.lint-go.result == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Set environment variables
        run: |
          echo "LOG_LEVEL=1" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run Tests
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
        run: ./run test
